import { jsPDF } from "jspdf";
import bwipjs from "bwip-js/browser";

export interface LabelSpec {
  name: string;
  title: string;
  price: number;
  barcode: string;
  size?: string | null;
}

/**
 * Render one or more 50×30mm sticker labels into a single multi-page PDF.
 * Each label fills exactly one page — perfect for a Zebra-style label printer.
 */
export async function renderBarcodeLabelsPdf(
  labels: LabelSpec[],
  copiesPerLabel: number = 1,
): Promise<Uint8Array> {
  if (labels.length === 0) {
    throw new Error("renderBarcodeLabelsPdf: no labels to print");
  }

  const pageWidth = 50; // mm
  const pageHeight = 30; // mm

  const doc = new jsPDF({
    unit: "mm",
    format: [pageWidth, pageHeight],
    orientation: "landscape",
  });

  let firstPage = true;

  for (const label of labels) {
    const dataUrl = await renderBarcodePng(label.barcode);

    for (let copy = 0; copy < copiesPerLabel; copy++) {
      if (!firstPage) doc.addPage([pageWidth, pageHeight], "landscape");
      firstPage = false;

      const cx = pageWidth / 2;
      let y = 2.5;

      // Product name (bold, may wrap to 2 lines)
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7);
      const nameLines = doc.splitTextToSize(label.name, pageWidth - 4).slice(0, 2);
      doc.text(nameLines, cx, y + 2, { align: "center" });
      y += nameLines.length * 2.6 + 0.5;

      // Title (lighter, single line)
      if (label.title && label.title !== label.name) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(5.5);
        doc.setTextColor(80);
        const titleLine = doc.splitTextToSize(label.title, pageWidth - 4)[0] ?? "";
        doc.text(titleLine, cx, y + 1.5, { align: "center" });
        y += 2.2;
        doc.setTextColor(0);
      }

      // Price + size badge on one line
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      const priceText = `Rs. ${Number(label.price).toLocaleString("en-PK", {
        maximumFractionDigits: 2,
      })}`;
      if (label.size) {
        const sizeText = `SIZE ${label.size}`;
        const priceWidth = doc.getTextWidth(priceText);
        const sizeWidth = doc.getTextWidth(sizeText) + 2.5;
        const totalWidth = priceWidth + sizeWidth + 1.5;
        const startX = cx - totalWidth / 2;
        doc.text(priceText, startX, y + 2.5);
        // Boxed size badge
        doc.setLineWidth(0.2);
        doc.rect(startX + priceWidth + 1.5, y + 0.3, sizeWidth, 2.8);
        doc.setFontSize(6.5);
        doc.text(sizeText, startX + priceWidth + 1.5 + sizeWidth / 2, y + 2.4, {
          align: "center",
        });
      } else {
        doc.text(priceText, cx, y + 2.5, { align: "center" });
      }
      y += 4;

      // Barcode image (PNG generated by bwip-js) + human-readable text
      const barcodeHeightMm = pageHeight - y - 1.2;
      const barcodeWidthMm = pageWidth - 4;
      doc.addImage(
        dataUrl,
        "PNG",
        (pageWidth - barcodeWidthMm) / 2,
        y,
        barcodeWidthMm,
        Math.max(8, barcodeHeightMm),
      );
    }
  }

  return new Uint8Array(doc.output("arraybuffer"));
}

async function renderBarcodePng(text: string): Promise<string> {
  // Off-screen canvas — bwip-js draws crisp Code 128 with the human-readable
  // text included so it matches what the on-screen labels look like.
  const canvas = document.createElement("canvas");
  bwipjs.toCanvas(canvas, {
    bcid: "code128",
    text,
    scale: 4,
    height: 12,
    includetext: true,
    textxalign: "center",
    textsize: 9,
    paddingwidth: 4,
    paddingheight: 2,
    backgroundcolor: "FFFFFF",
  });
  return canvas.toDataURL("image/png");
}
